(function () {
    var app = angular.module('Dish', []);
    app.controller('DishController', function ($scope) {
        this.dishes = gem;
    });

    var gem = [{
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '羊肉',
        quantity: 3,
        finish: true,
        remark: "要筋肉多点"
    }, {
        tableNo: 1,
        name: '牛肉',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 3,
        name: '羊肉',
        quantity: 2,
        finish: true,
        remark: "要肥肉多点"
    }, {
        tableNo: 1,
        name: '香菇',
        quantity: 1,
        finish: true,
        remark: ""
    }, {
        tableNo: 1,
        name: '鸡毛菜',
        quantity: 2,
        finish: true,
        remark: ""
    }]
})();