(function () {
    var app = angular.module('Serve', []);
    app.controller('ServeController', function ($scope) {
        this.tables = gem;
    });

    var gem = [
        {
            no: 3,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            },{
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 2,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 1,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 4,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 5,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 6,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }, {
            no: 7,
            finish: false,
            dishes: [{
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }, {
                name: '牛肉',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '香菇',
                quantity: 1,
                finish: true,
                remark: ""
            }, {
                name: '鸡毛菜',
                quantity: 2,
                finish: true,
                remark: ""
            }, {
                name: '羊肉',
                quantity: 3,
                finish: true,
                remark: "要筋肉多点"
            }]
        }
    ];
})();