(function () {
    var app = angular.module('Store', []);
    app.controller('StoreController', function ($scope) {
        this.tables = gem;
    });

    var gem = [{
        no: 1,
        name: '西瓜',
        people: 4,
        size: "middle",
        full: true,
        datetime: "19:30:15",
    }, {
        no: 2,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 3,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 4,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 5,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 6,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 7,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 8,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 9,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 10,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 11,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 12,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 13,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 14,
        name: '西瓜',
        people: 2,
        size: "small",
        full: false,
        datetime: ""
    }, {
        no: 15,
        name: '西瓜',
        people: 8,
        size: "big",
        full: false,
        datetime: ""
    }, {
        no: 16,
        name: '西瓜',
        people: 4,
        size: "middle",
        full: false,
        datetime: ""
    }]
})();